tags:
  - name: Products
    description: Product CRUD operations

paths:
  /api/getProducts:
    get:
      tags: [Products]
      summary: Get all products
      parameters:
        - in: query
          name: category
          schema:
            type: string
        - in: query
          name: priceMin
          schema:
            type: number
        - in: query
          name: priceMax
          schema:
            type: number
        - in: query
          name: name
          schema:
            type: string
        - in: query
          name: page
          schema:
            type: integer
        - in: query
          name: limit
          schema:
            type: integer
      responses:
        200:
          description: Successful response

  /api/createProduct:
    post:
      tags: [Products]
      summary: Create a product
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [name, price, category]
              properties:
                name:
                  type: string
                price:
                  type: number
                category:
                  type: string
                description:
                  type: string
      responses:
        201:
          description: Product created

  /api/updateProduct/{id}:
    put:
      tags: [Products]
      summary: Update a product
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                price:
                  type: number
                category:
                  type: string
      responses:
        200:
          description: Product updated

  /api/deleteProduct/{id}:
    delete:
      tags: [Products]
      summary: Delete a product
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        200:
          description: Product deleted
